- .storybook/manager-head.html
- .storybook/manager.js
- .storybook/preview-head.html
- src/styles/global-css-settings.scss
- src/styles/states.scss
https://monday.monday.com/boards/3532714909/pulses/4983399866
> Chore: storybook infra cleanup + variables cleanup

- src/styles/tokens/colors.scss
https://monday.monday.com/boards/3532714909/pulses/5083683097
> Add mising color tokens

- .storybook/preview-head.html
- src/styles/tokens/typography.scss
https://monday.monday.com/boards/3532714909/pulses/5254168089
> Replace Rubik with Noto Sans Hebrew

- .github/workflows/test-workflow.yml
https://monday.monday.com/boards/3532714909/pulses/4909393748
> infra: test-workflow.yml - remove push trigger

- COMPONENTS_DOCUMENTATION_GUIDELINES.md
- CONTRIBUTING.md
https://monday.monday.com/boards/3532714909/pulses/5273249054
https://monday.monday.com/boards/3532714909/pulses/5273249054
Theming coverage will be added later in the corresponding task https://monday.monday.com/boards/3532714909/pulses/5273244411
> docs: contibuting.md + components_documentation_guidelines.md

- src/functions/createStoryMetaSettings.js
https://monday.monday.com/boards/3532714909/pulses/5280802624
> feat: createMetastorySettings - string type for ContentElement controls, disable action controls

- src/components/status-tag/__stories__/status-tag.mdx
- src/components/status-tag/__stories__/status-tag.stories.tsx
- src/components/status-tag/status-tag.module.scss
- src/components/status-tag/status-tag.tsx
- src/styles/tokens/colors.scss
Had a mess in the other branch so created a new one 😅 
https://monday.monday.com/boards/3532714909/pulses/4794600988
Replaces #31
> feat: add StatusTag

- src/components/alpha-warning/alpha-warning.tsx
- src/components/deprecated-warning/deprecated-warning.tsx
- src/components/status-tag/__stories__/status-tag.stories.tsx
- src/components/tip/__stories__/tip.stories.tsx
- src/components/tip/tip.tsx
- src/helpers/components/Flex/Flex.tsx
- src/helpers/components/Link/Link.tsx
- src/types/withStaticProps.ts
https://monday.monday.com/boards/3532714909/pulses/5294594682
> Export components withStaticProps

- CSS_MODULES_MIGRATION.md
https://monday.monday.com/boards/3532714909/pulses/5294646449
> docs: CSS_MODULES_MIGRATION.md

- src/components/index.ts
- src/components/sidebar-item/__stories__/sidebar-item.mdx
- src/components/sidebar-item/__stories__/sidebar-item.stories.tsx
- src/components/sidebar-item/sidebar-item.tsx
- storybook/components/component-name/component-name-decorator.jsx
- storybook/components/index.js
I added the additional component for the sidebar tags because of issues with CSS modules and SCSS in the Storybook consumer, to avoid this I added this component so it will be easier to consume it
https://monday.monday.com/boards/3532714909/views/80492475/pulses/4794600988
> Add sidebar item

- src/components/title/title.jsx
- src/components/title/title.module.scss
- src/components/unstyled-list-item/unstyled-list-item.jsx
- src/components/unstyled-list-item/unstyled-list-item.module.scss
- src/components/unstyled-list/unstyled-list.jsx
> CSS modules migration: < UnstyledList />, < UnstyledListItem />, < Title /> 

- src/components/doc-footer/doc-footer.tsx
- src/components/frame/frame.tsx
- src/components/paragraph/paragraph.jsx
- src/components/paragraph/paragraph.tsx
- src/components/section-name/section-name.tsx
Fixed #39 
Migrated all the mentioned components and child components to TS
> Migrated < DocFooter />, < Frame />, < Paragraph /> and also child component <SectionName /> to TS

- src/components/usage-guidelines/usage-guidelines.tsx
- src/components/visual-description/visual-description.tsx
> TS migration: < UsageGuidelines />, < VisualDescription />

- .github/workflows/test-workflow.yml
https://monday.monday.com/boards/3532714909/pulses/5333885530
> infra: add build into test-workflow.yml

- src/components/related-component/related-component.tsx
- src/components/related-components/related-components.tsx
- src/components/section-name/section-name.tsx
> TS migration: < SectionName />, < RelatedComponent />, < RelatedComponents />

- src/components/component-rule/component-rule.module.scss
- src/components/component-rule/component-rule.tsx
- src/components/component-rules/component-rules.module.scss
- src/components/component-rules/component-rules.tsx
> feat: Migrate < ComponentRule />, < ComponentRules /> to css modules

- src/components/component-name/__stories__/component-name.mdx
- src/components/component-name/__stories__/component-name.stories.tsx
> docs: Add story for < ComponentName /> component

- src/components/anchor-list-item/anchor-list-item.module.scss
- src/components/anchor-list-item/anchor-list-item.tsx
- src/components/component-name/component-name.module.scss
- src/components/component-name/component-name.tsx
- src/components/doc-footer/doc-footer.module.scss
- src/components/doc-footer/doc-footer.tsx
> Migrated < AnchorListItem />, < ComponentName />, < DocFooter /> to CSS modules

- src/components/component-name/component-name.module.scss
removed accidently after external contribution
> fix: < ComponentName /> use text-color-fixed-dark

- src/functions/createComponentTemplate.jsx
- src/functions/createComponentTemplate.tsx
- src/functions/createStoryMetaSettings.ts
Fixes #80 
@SergeyRoyt - I have updated the component to TS. but not sure about some the types of the storybooks to be used. So kept it as any and due to that there are lint error which need to be resolved.
Let me know if have any details about these types.
> Migrated the component to TS

- src/components/frame/__stories__/frame.mdx
- src/components/frame/__stories__/frame.stories.tsx
- src/components/paragraph/__stories__/paragraph.mdx
- src/components/paragraph/__stories__/paragraph.stories.tsx
> Created story from Paragraph and Frame components

- src/components/token-table/__stories__/token-table.mdx
- src/components/token-table/__stories__/token-table.stories.tsx
Closes #90
Added story for `<TokenTable/>` component.
> docs: add story for < TokenTable />

- src/components/component-description/__stories__/component-description.mdx
- src/components/component-description/__stories__/component-description.stories.tsx
- src/components/unstyled-list/__stories__/unstyled-list.mdx
- src/components/unstyled-list/__stories__/unstyled-list.stories.tsx
Closes #89
- Added stories for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />
> docs: create basic story for < ComponentDescription />, < UnstyledList /> + < UnstyledListItem />

- src/components/color-description/color-description.module.scss
- src/components/color-description/color-description.scss
- src/components/color-description/color-description.tsx
Closes #101 
- Migrate <ColorDescription/> to css modules
> chore: migrate <ColorDescription/> to css modules

- src/components/sidebar-item/sidebar-item.module.scss
- src/components/sidebar-item/sidebar-item.tsx
Had some issue because of the way Storybook wraps this component
https://monday.monday.com/boards/3532714909/pulses/5372789556
> fix(SidebarItem): flex the container

- src/components/component-rules/__stories__/component-rules.mdx
- src/components/component-rules/__stories__/component-rules.stories.tsx
- src/components/doc-footer/__stories__/doc-footer.mdx
- src/components/doc-footer/__stories__/doc-footer.stories.tsx
Closes #102
- Added story for `< ComponentRules />` and `< DocFooter />` components
> docs: add story for < ComponentRules />, < DocFooter />

- src/components/anchor-list-item/__stories__/anchor-list-item.mdx
- src/components/anchor-list-item/__stories__/anchor-list-item.stories.tsx
- src/components/section-name/__stories__/section-name.mdx
- src/components/section-name/__stories__/section-name.stories.tsx
> Created basic story for < SectionName />, < AnchorListItem />

- src/components/title/__stories__/title.mdx
- src/components/title/__stories__/title.stories.tsx
> Add story for < Title /> component

- src/components/function-arguments/__stories__/function-arguments.mdx
- src/components/function-arguments/__stories__/function-arguments.stories.tsx
- src/components/function-arguments/function-argument.tsx
- src/components/information-box/__stories__/information-box.mdx
- src/components/information-box/__stories__/information-box.stories.tsx
Closes #103
- Added stories for `< FunctionArguments />` and `< InformationBox />`
> docs: add story for < FunctionArguments /> and < InformationBox />

- src/components/component-rule/component-rule.tsx
- src/components/component-rules/component-rules.tsx
- src/components/information-box/information-box.tsx
dummy changes in order to release a new version
> chore: cleanup

- src/components/information-box-title/information-box-title.tsx
- src/components/related-component/related-component.tsx
https://monday.monday.com/boards/3532714909/pulses/5484669502
> fix: <InformationBoxTitle> use <Link>

- .storybook/preview-head.html
- .storybook/preview.tsx
https://monday.monday.com/boards/3532714909/pulses/5484481728
> docs: remove hacker theme from storybook

- src/components/doc-footer/doc-footer.tsx
https://monday.monday.com/boards/3532714909/pulses/5484670497
> fix: <DocFooter> use <Link>

- src/components/information-box-title/information-box-title.tsx
https://monday.monday.com/boards/3532714909/pulses/5484669502
> fix: <InformationBoxTitle> Link withoutSpacing

- src/components/information-box/information-box.module.scss
- src/styles/tokens/typography.scss
https://monday.monday.com/boards/3532714909/pulses/5331797912
> fix: reduce <InformationBox> line-height from 24px to 20px

- src/components/link/LinkConstants.ts
- src/components/link/link.tsx
https://monday.monday.com/boards/3532714909/pulses/5516570884
> feat: <Link> add target prop

- src/components/deprecated-warning/deprecated-warning.tsx
https://monday.monday.com/boards/3532714909/pulses/5539018000
> feat(DeprecatedWarning): add children

- src/components/sidebar-item/sidebar-item.module.scss
https://monday.monday.com/boards/3532714909/pulses/5615112278
> fix(SidebarItem): add margin to the right
